### ISSUE TITLE
Dotfile (.DS_Store) in template folder lead to exit

### ISSUE THREAD

**Issue by khorolets** [khorolets/workbench2#1]
The code

```rust
let tera = compile_templates!("templates/**/*");
```

leads to exit if it can't parse Jinja2 template successfully. According to the fact that this macro compiles all the files in `template` folder it crashes when see for example a dotfile such as `.DS_Store`.

Need to deal with it somehow. At least show an error instead of exit.

**Comment by frol** [comment]
Can't you compile only `*.html` files? (`templates/**/*.html`)

**Comment by khorolets** [comment]
@frol Thank you, it's really obvious solution indeed :)
